name: Rust

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - run: |
        pushd ${{ github.workspace }}
        cd downloader
        cargo run --release
        popd
        pushd ${{ github.workspace }}
        cd installer
        cargo run --release ${{ secrets.INSTALLER_ARGS }}
        mv "Kaizo Mario 3D World.exe" ${{ github.workspace }}
        popd
        pushd ${{ github.workspace }}
        cd updater
        cargo build --release
        cd target
        cd release
        mv updater.exe ${{ github.workspace }}
        popd
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        #Change this when Surf updates Kaizo finally.
        automatic_release_tag: "2.69"
        prerelease: false
        title: "Version 2.69"
        files: |
          *.exe
