[package]
name = "installer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "0.3.0"
zip-extract = "0.1.1"
downloader = { version = "0.1.0", path = "../downloader" }

[build-dependencies]
